services:
  app:
    build:
      context: .
    depends_on:
      - db
    #   - redis
    ports:
      - "3000:3000"
    volumes:
      - .:/rails-varnish
      - gem_cache:/usr/local/bundle/gems
    environment:
      RAILS_ENV: development
  db:
    image: postgres:15.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
  varnish:
    build:
      context: .
      dockerfile: Dockerfile.varnish
    container_name: varnish
    volumes:
      - "./varnish/default.vcl:/etc/varnish/default.vcl"
    ports:
      - "8080:80"
    tmpfs:
      - /var/lib/varnish:exec
    environment:
      - VARNISH_SIZE=2G
    command: -p feature=+esi_disable_xml_check -p feature=+esi_ignore_other_elements
    depends_on:
      - "app"

volumes:
  gem_cache:
