version: '3.4'
services:
  app:
    build:
      context: .
    depends_on:
      - database
    #   - redis
    ports:
      - "3000:3000"
    volumes:
      - .:/rails-varnish
      - gem_cache:/usr/local/bundle/gems
    environment:
      RAILS_ENV: development
  database:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/
  varnish:
    build:
      context: .
      dockerfile: Dockerfile.varnish
    container_name: varnish
    volumes:
      - "./varnish/default.vcl:/etc/varnish/default.vcl"
    ports:
      - "8080:80"
    tmpfs:
      - /var/lib/varnish:exec
    environment:
      - VARNISH_SIZE=2G
    command: "-p default_keep=300"
    depends_on:
      - "app"

volumes:
  gem_cache:
